dielectric_constants:
  DIELECTRIC: 11.0
  HELIUM: 1.057
  METAL: 1.0
  VACUUM: 1.0
extract_opt:
- additional_name: Sandia
  coordinate1:
  - -695
  - -662
  - 301
  coordinate2:
  - 135
  - 140
  - 1001
  coordinate3: 2.13
  plane: xy
  quantity: phi
ff_polynomial: 2
meshfile: Sandia
physicalSurfaces:
  CCD1: 7
  CCD2: 6
  CCD3: 5
  DR2: 9
  DR3: 8
  Dr1: 10
  Reservoir: 11
  TopMetal: 12
physicalVolumes:
  DIELECTRIC: 4
  HELIUM: 1
  METAL: 2
  VACUUM: 3
