function [xDataCell,yDataCell,xLab,yLab,titleName] = pullSR830Data(figNum,plotName,pullForwardAndBack)
    % Pulls x and y data of sub plots generated by SR830 data sets. Sorts
    % the data into a cell of arrays. Use cells to plot data directly. Note
    % that all data and plots are in reverse order e.g forward graphs are
    % index 2 while back graphs are index 1 (this is just the way we set up
    % our plotting). 
    %
    % Inputs: 
    %       figNum - desired figure number to get data from
    %       plotName - desired subplot number to get data from. Valid
    %       inputs are: 'Mag vs Bias', 'Imag vs Bias', 'Real vs Bias', 'Mag
    %       vs Time', 'Imag vs Time', and 'Real vs Time'.

    figPathCell = findFigNumPath(figNum);
    figPath = figPathCell{1};
    
    switch plotName
        case 'Mag vs Bias'
            plotNum = 1;
            type = 'ErrorBar';
        case 'Imag vs Bias'
            plotNum = 2;
            type = 'ErrorBar';
        case 'Real vs Bias'
            plotNum = 3;
            type = 'ErrorBar';
        case 'Mag vs Time'
            plotNum = 4;
            type = 'Line';
        case 'Imag vs Time'
            plotNum = 5;
            type = 'Line';
        case 'Real vs Time'
            plotNum = 6;
            type = 'Line';

        otherwise
            disp(["The plot you desire does not have the title: ",plotName])
            
    end

    if plotNum < 4 && pullForwardAndBack
        % backward graph!
        [xDat,yDat,~,~,~] = getXYDataSubPlots(figPath,'plotNum',plotNum,'fieldNum',1,'type',type);
        % forward graph!
        [xDat2,yDat2,xLab,yLab,titleName] = getXYDataSubPlots(figPath,'plotNum',plotNum,'fieldNum',2,'type',type);
        xDataCell = {xDat,xDat2};
        yDataCell = {yDat,yDat2};
    elseif plotNum < 4 && ~pullForwardAndBack
            % forward graph!
            [xDat,yDat,xLab,yLab,titleName] = getXYDataSubPlots(figPath,'plotNum',plotNum,'fieldNum',2,'type',type);
            xDataCell = {xDat};
            yDataCell = {yDat};
    else
        [xDat,yDat,xLab,yLab,titleName] = getXYDataSubPlots(figPath,'plotNum',plotNum,'fieldNum',1,'type',type);
        xDataCell = {xDat};
        yDataCell = {yDat};
    end

end

